import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib
import json

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from tensorflow.keras.models import load_model

from tensorflow.keras.layers import Dense

class CustomDense(Dense):
    def __init__(self, *args, **kwargs):
        kwargs.pop('quantization_config', None)
        super().__init__(*args, **kwargs)

# =========================
# 1. LOAD DATA & CLEAN
# =========================
df = pd.read_csv("traffic_output.csv")

if 'id' in df.columns:
    df = df.drop(columns=['id'])

# Drop rows with missing values
df = df.dropna().copy()

# =========================
# 2. FEATURE ENGINEERING (Identical to lstm.py)
# =========================
df['date'] = pd.to_datetime(df['date'])
df['time_orig'] = pd.to_datetime(df['time'], format='%H:%M')

df['direction_orig'] = df['direction']
df['hour'] = df['time_orig'].dt.hour
df['minute'] = df['time_orig'].dt.minute

df['is_weekend'] = (df['date'].dt.dayofweek >= 5).astype(int)
df['sin_hour'] = np.sin(2 * np.pi * df['hour'] / 23.0)
df['cos_hour'] = np.cos(2 * np.pi * df['hour'] / 23.0)
df['sin_min'] = np.sin(2 * np.pi * df['minute'] / 59.0)
df['cos_min'] = np.cos(2 * np.pi * df['minute'] / 59.0)
df['day_of_week'] = df['date'].dt.dayofweek + 1

df = pd.get_dummies(df, columns=['timezone', 'direction'], drop_first=False)
df = df.drop(columns=['time', 'hour', 'minute'])

for col in df.columns:
    if df[col].dtype == bool:
        df[col] = df[col].astype(int)

# =========================
# 3. TEST SPLIT
# =========================
unique_dates = df['date'].sort_values().unique()
split_idx = int(len(unique_dates) * 0.8)
split_date = unique_dates[split_idx]

test_df = df[df['date'] >= split_date].copy()

# =========================
# 4. LOAD SCALER AND SCALE
# =========================
target_cols = ['motorcycle', 'car', 'bus', 'truck']
y_scaler = joblib.load("y_scaler.pkl")

test_df[target_cols] = y_scaler.transform(test_df[target_cols])

# =========================
# 5. SEQUENCE GENERATION
# =========================
sequence_length = 4

def create_sequences(data_split):
    X_seq, y_seq = [], []
    feature_cols = [c for c in data_split.columns if c not in ['date', 'time_orig', 'direction_orig']]
    
    for direction in data_split['direction_orig'].unique():
        dir_df = data_split[data_split['direction_orig'] == direction].sort_values(by=['date', 'time_orig'])
        
        dir_values = dir_df[feature_cols].values
        dir_targets = dir_df[target_cols].values
        
        for i in range(sequence_length, len(dir_values)):
            X_seq.append(dir_values[i-sequence_length:i])
            y_seq.append(dir_targets[i])
            
    return np.array(X_seq), np.array(y_seq)

X_test, y_test = create_sequences(test_df)
# Use all features as generated by the preprocessing pipeline
# X_test shape is (samples, sequence_length, features)

# =========================
# 6. LOAD MODEL & EVALUATE
# =========================
# Use custom_objects if the model was saved with custom layers, 
# although in lstm.py it was standard Dense.
try:
    model = load_model("traffic_lstm_model.keras", custom_objects={'Dense': CustomDense}, compile=False)
except:
    model = load_model("traffic_lstm_model.h5", custom_objects={'Dense': CustomDense}, compile=False)

predictions = model.predict(X_test)

# Convert back to original scale
predictions_actual = y_scaler.inverse_transform(predictions)
y_test_actual = y_scaler.inverse_transform(y_test)

metrics = {}
for i, cat in enumerate(target_cols):
    y_true = y_test_actual[:, i]
    y_pred = predictions_actual[:, i]
    
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    
    metrics[cat] = {
        "MAE": float(mae),
        "RMSE": float(rmse),
        "R2": float(r2)
    }
    
with open("metrics.json", "w") as f:
    json.dump(metrics, f, indent=4)

# =========================
# 7. GENERATE MULTI-PANEL PLOT
# =========================
subset_len = min(150, len(y_test_actual))

fig, axes = plt.subplots(2, 2, figsize=(16, 10))
axes = axes.flatten()

for i, cat in enumerate(target_cols):
    ax = axes[i]
    ax.plot(y_test_actual[:subset_len, i], label=f'Actual {cat.capitalize()}', color='green', marker='o', markersize=3, linestyle='-')
    ax.plot(predictions_actual[:subset_len, i], label=f'Predicted {cat.capitalize()}', color='red', marker='x', markersize=3, linestyle='--')
    ax.set_title(f'Traffic Trend: Actual vs Predicted ({cat.capitalize()})')
    ax.set_xlabel('Time Sequence')
    ax.set_ylabel('Vehicle Count')
    ax.legend()
    ax.grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.savefig("lstm_evaluation_plot.png")
print("Evaluation complete. Metrics saved to metrics.json and plot saved to lstm_evaluation_plot.png")
